[hardware-config]
n_gpus = 1

[network-config]
HPC_ip = "172.16.1.32"
HPC_port = 8888
DDP_ip = "127.0.0.1"
DDP_port = 3241
router_port = 5555
envs_base_port = 5000
envs_connection_timeout = 60
bind_retry_timeout = 5
envs_logger_base_port = 6000
logger_port = 9000

[backup-logs]
data_path = "/home/jul/Desktop/TEST" #/home/jul/NetDrives/AI-Storage/J0HNMELEE
show_instances_id_as = "IP" #IP/PORT/ID
save_logs_every = 0.5 #seconds
csv_logs_filename = "J0HNMelee_[ID]_[d].[mo].[y]"
instances_filter_mode = "WHITELIST" # WHITELIST/BLACKLIST
instances_filtered = [0] # instances id in the [instances] list
weights_dir_name = "J0HNMelee_[d].[mo].[y]_[h]:[mi]:[s]"
save_weights_every = 3600 #seconds
load_weights_on_startup = false
weights_to_load = "LAST" #FIRST/LAST/(name of specific weights)$
score_history_csv_name = "SCORE_HISTORY_J0HNMelee_[d].[mo].[y]_[h]:[mi]:[s]"

[training-config]
n_epochs = 15
batch_size = 128
learn_steps = 2048
n_games = 50
n_projectiles = 5

[agent]
gamma = 0.99
actor_lr = 0.0003
critic_lr = 0.0003
gae = 0.95
policy_clip = 0.2
gradient_clip = 0.5

[actor_model]
hidden_layers = [4096, 4096, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]
add_LayerNorm = true
activation = "ReLU"
 
[critic_model]
hidden_layers = [4096, 4096, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]
add_LayerNorm = true
activation = "ReLU"

[reward-settings]
#agent_punch_power_modifier = 1
#cpu_punch_power_modifier = 7
#agent_combo_modifier = 20
#cpu_combo_modifier = 200
#sub_frame_damage_modifier = 0.001
#percent_modifier = 30
#agent_reward_overflow = 100000
#cpu_reward_overflow = 100000
#agent_percent_difference_modifier = 5
#cpu_percent_difference_modifier = 1
#agent_winner_reward = 0
#cpu_winner_reward = 0
#agent_idle_modifier = 0.8
#agent_idle_penalty_start = 60
#agent_stock_penalty_modifier = 1
#cpu_stock_penalty_modifier = 1.2
#reward_set = [-50000,10000]
#reward_reducer = 10
agent_win_reward = 500
cpu_win_reward = -500
agent_percent_lost_penalty = 2
cpu_lost_percent_bonus = 2

[instances]

[instances.0]
ip = "172.16.1.120"
stage = "FINAL_DESTINATION"
agent_character = "MARIO"
cpu_character = "LUIGI"
cpu_level = 1

stage_change_rate = 5 # Changes stage every x games (0 for no change)
agent_character_change_rate = 10 # Changes character every x games (0 for no change)
cpu_character_change_rate = 3 # Changes character every x games (0 for no change)
minimum_games_berfore_changing_cpu_level = 3
cpu_level_progression_rate = 0.6 # Changes cpu level when the AI V/D ratio is greater than this value (0 for no change)
max_cpu_level = 1