[hardware-config]
n_gpus = 2

[network-config]
HPC_ip = "172.16.1.32"
HPC_port = 8888
DDP_ip = "127.0.0.1"
DDP_port = 3241
router_port = 5555
envs_base_port = 5000
envs_connection_timeout = 60
bind_retry_timeout = 5
envs_logger_base_port = 6000
logger_port = 9000

[backup-logs]
data_path = "/home/jul/NetDrives/AI-Storage/J0HNMELEE"
show_instances_id_as = "IP" #IP/PORT/ID

[training-config]
n_epochs = 40
batch_size = 1024
world_size = 24
learn_steps = 30
n_games = 50
n_projectiles = 3

[agent]
gamma = 0.999  
actor_lr = 0.0003
critic_lr = 0.0003
gae = 0.95
policy_clip = 0.2

[reward-settings]
agent_punch_power_modifier = 2
cpu_punch_power_modifier = 2
agent_combo_modifier = 60
cpu_combo_modifier = 120
sub_frame_damage_modifier = 0.001
percent_modifier = 20
agent_win_reward = 100
cpu_win_reward = 100

[instances]

[instances.0]
ip = "172.16.1.120"
stage = "FINAL_DESTINATION"
agent_character = "MARIO"
cpu_character = "LUIGI"
cpu_level = 1

stage_change_rate = 2 # Changes stage every x games (0 for no change)
agent_character_change_rate = 3 # Changes character every x games (0 for no change)
cpu_character_change_rate = 3 # Changes character every x games (0 for no change)
minimum_games_berfore_changing_cpu_level = 3
cpu_level_progression_rate = 0.6 # Changes cpu level when the AI V/D ratio is greater than this value (0 for no change)
max_cpu_level = 9